### ISSUE TITLE
Getting error when following readme to install the server script

### ISSUE THREAD

**Issue by codelock13** [schollz/snaptext#3]
I am getting error as github.com/schollz/snaptext/src not found.can you explain me how can I install script on service such as heroku where also I am  getting error.

**Comment by tscholl2** [comment]
Hi, I was able to reproduce your error running. The docs should probably be updated. Try running this first:

```
go get -v github.com/schollz/snaptext
```

That should install the `snaptext` binary. But you will need to run it from the `$GOPATH/github.com/schollz/snaptext` directory I think. That seemed to get it running. But I'm not sure if that's totally correct, because there is also a `Makefile` in the repo, so you may have to build it manually. That requires installing `go-bindata` which you should be able to do with `go get -u github.com/jteeuwen/go-bindata/...`.

**Comment by schollz** [comment]
@codelock13 Yeah I needed to bundle the bindata which I did in https://github.com/schollz/snaptext/commit/18ace6e967a3c6f0f006ec209aba83a390bd0cb2, so now it should work with just `go get -v github.com/schollz/snaptext`.

I'm not sure how to use it on heroku, I've never used it before, but you should just be able to follow the README to run.

**Comment by codelock13** [comment]
Hey how did you host the script?

**Comment by codelock13** [comment]
i am getting folowing error while running script please help

panic: html/template: pattern matches no files: `templates/*`

goroutine 1 [running]:
panic(0x5f7f90, 0x10c0d718)
	/usr/lib/go-1.7/src/runtime/panic.go:500 +0x33c
html/template.Must(0x0, 0x893ef8, 0x10c0d718, 0x0)
	/usr/lib/go-1.7/src/html/template/template.go:340 +0x4c
github.com/schollz/snaptext/vendor/github.com/gin-gonic/gin.(*Engine).LoadHTMLGlob(0x10c6f220, 0x673b6f, 0xb)
	/home/pi/go/src/github.com/schollz/snaptext/vendor/github.com/gin-gonic/gin/gin.go:181 +0xc78
github.com/schollz/snaptext/src.Run(0x66d335, 0x4, 0x0, 0x0)
	/home/pi/go/src/github.com/schollz/snaptext/src/server.go:49 +0xe4
main.main()
	/home/pi/go/src/github.com/schollz/snaptext/main.go:22 +0xb4

**Comment by codelock13** [comment]
can you plz  help me by creating an image for pi zero or 3
with script running

**Comment by schollz** [comment]
Here you can download the raspberry pi version: https://github.com/schollz/snaptext/releases/latest

**Comment by codelock13** [comment]
Thanks for your help I would learn go as fast as I can.can you help me .how you learnt it answer if you want.thanks again
